### PR TITLE
Update travis to test on multiple compilers

### PR DESCRIPTION
**Pull request by CamStan**
Getting Travis working again since migration to new repo.

This also tests the build across multiple compilers that are used on our machines.

### CODE REVIEW

**Comment by CamStan** [comment]
This does default to MPI being off. We could have this install mpi as well and build with it.

**Comment by adammoody** [comment]
We don't have any test cases that check MPI behavior right now.  It would be nice to know that the MPI portion of the code compiles, though.  We could handle that in a future PR if it's easier.

**Comment by CamStan** [comment]
True. This will at least give us something for now.

**Comment by CamStan** [comment]
Updated with MPI being on.

**Pull request merged**
