### PR TITLE
Add cmake config support

### PR DESCRIPTION
**Pull request by nmm0**
To make it easier to consume VELOC and its dependent libraries I suggest adding support for cmake configs. This is preferable to using Find modules since the upstream should maintain these configs. I was motivated to work on this since I am a maintainer of a library ([kokkos-resilience](https://github.com/kokkos/kokkos-resilience)) that consumes VELOC and it would simplify our build code significantly.

A couple of important notes on this PR -- When running cmake on the project I get warnings about using CMake 2.8, which was first released in 2009. I updated the required version of cmake in this PR to 3.17, which is commonly available at Sandia clusters but I don't know if you may have different requirements. The changes I made should work for earlier CMake versions so I can change it as needed. I don't think it's a good idea to go earlier than 3.10 however.

Another note is that currently the config can be found with `find_package(kvtree)`. I've seen in the other related project that typically you use `find_package(KVTREE)` (with the find module). I can rename the configs to `KVTREEConfig.cmake` if that's preferable; I just used the all lower case since that is common convention.

Finally I have patches for the other repos associated with VELOC and can contribute them if this PR is welcome.

### CODE REVIEW

**Comment by adammoody** [comment]
Thanks so much, @nmm0 !

We've talked about doing something like this several times within the team, but we've not had time to get to it.  I'd like to test this out myself and give others time to look it over, but I like this approach.

**Comment by adammoody** [comment]
Thanks again @nmm0 .  Others on the team also agree this looks good.  We'll merge this in.  Please go ahead and submit PRs for your other changes.  Thanks!

**Comment by adammoody** [comment]
I have newer cmake versions, but cmake 3.14 is the default on many systems that I use.  I might drop that minimum cmake version to 3.14 if it works.  That would save LLNL users a step.

**Comment by nmm0** [comment]
> I have newer cmake versions, but cmake 3.14 is the default on many systems that I use. I might drop that minimum cmake version to 3.14 if it works. That would save LLNL users a step.

Sounds good, I will update the other libraries before I submit the PRs (might not get to it until next week)

**Comment by gonsie** [comment]
Thanks for the PR! I've approved you for our CI. There was one error detected, but I just pushed a fix. Hopefully we can get everything passing to merge this in!

**Comment by nmm0** [comment]
> Woo! All tests are green white_check_mark grin
> 
> Please change the Cmake version to 3.14 and let us know when you are ready for a merge.

Done, thank you!

**Comment by adammoody** [comment]
Thanks again, @nmm0 .  And good catch, @gonsie

**Comment by adammoody** [comment]
@nmm0 , do you have time to submit your PRs for the other components, as well?

**Comment by nmm0** [comment]
> @nmm0 , do you have time to submit your PRs for the other components, as well?

@adammoody Yes, apologies -- I'm on travel right now but I will submit when I get back.

**Comment by adammoody** [comment]
Oh great, thank you, @nmm0 .  Happy travels!

**Pull request merged**
